from typing import overload

import numpy as np
import pandas as pd
import polars as pl

@overload
def add(a: pl.Expr, b: pl.Expr) -> pl.Expr: ...
@overload
def add(a: str, b: str) -> pl.Expr: ...
@overload
def add(a: pl.Series, b: pl.Series) -> pl.Series: ...
@overload
def add(a: pd.Series, b: pd.Series) -> pd.Series: ...
@overload
def add(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...
@overload
def add(a: float, b: float) -> float | None: ...
@overload
def scale(col: pl.Expr, factor: float) -> pl.Expr: ...
@overload
def scale(col: str, factor: float) -> pl.Expr: ...
@overload
def scale(col: pl.Series, factor: float) -> pl.Series: ...
@overload
def scale(col: pd.Series, factor: float) -> pd.Series: ...
@overload
def scale(col: np.ndarray, factor: float) -> np.ndarray: ...
@overload
def scale(col: float, factor: float) -> float | None: ...
@overload
def add_optional(a: pl.Expr, b: pl.Expr | None = None) -> pl.Expr: ...
@overload
def add_optional(a: str, b: str | None = None) -> pl.Expr: ...
@overload
def add_optional(a: pl.Series, b: pl.Series | None = None) -> pl.Series: ...
@overload
def add_optional(a: pd.Series, b: pd.Series | None = None) -> pd.Series: ...
@overload
def add_optional(a: np.ndarray, b: np.ndarray | None = None) -> np.ndarray: ...
@overload
def add_optional(a: float, b: float | None = None) -> float | None: ...
@overload
def offset(col: pl.Expr, by: pl.Expr | float) -> pl.Expr: ...
@overload
def offset(col: str, by: str | float) -> pl.Expr: ...
@overload
def offset(col: pl.Series, by: pl.Series | float) -> pl.Series: ...
@overload
def offset(col: pd.Series, by: pd.Series | float) -> pd.Series: ...
@overload
def offset(col: np.ndarray, by: np.ndarray | float) -> np.ndarray: ...
@overload
def offset(col: float, by: float) -> float | None: ...
@overload
def offset_optional(col: pl.Expr, by: pl.Expr | float | None = None) -> pl.Expr: ...
@overload
def offset_optional(col: str, by: str | float | None = None) -> pl.Expr: ...
@overload
def offset_optional(col: pl.Series, by: pl.Series | float | None = None) -> pl.Series: ...
@overload
def offset_optional(col: pd.Series, by: pd.Series | float | None = None) -> pd.Series: ...
@overload
def offset_optional(col: np.ndarray, by: np.ndarray | float | None = None) -> np.ndarray: ...
@overload
def offset_optional(col: float, by: float | None = None) -> float | None: ...
