from typing import overload

import numpy as np
import pandas as pd
import polars as pl

@overload
def add(a: pl.Expr, b: pl.Expr) -> pl.Expr: ...
@overload
def add(a: str, b: str) -> pl.Expr: ...
@overload
def add(a: pl.Series, b: pl.Series) -> pl.Series: ...
@overload
def add(a: pd.Series, b: pd.Series) -> pd.Series: ...
@overload
def add(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...
@overload
def scale(col: pl.Expr, factor: float) -> pl.Expr: ...
@overload
def scale(col: str, factor: float) -> pl.Expr: ...
@overload
def scale(col: pl.Series, factor: float) -> pl.Series: ...
@overload
def scale(col: pd.Series, factor: float) -> pd.Series: ...
@overload
def scale(col: np.ndarray, factor: float) -> np.ndarray: ...
@overload
def add_optional(a: pl.Expr, b: pl.Expr | None = None) -> pl.Expr: ...
@overload
def add_optional(a: str, b: str | None = None) -> pl.Expr: ...
@overload
def add_optional(a: pl.Series, b: pl.Series | None = None) -> pl.Series: ...
@overload
def add_optional(a: pd.Series, b: pd.Series | None = None) -> pd.Series: ...
@overload
def add_optional(a: np.ndarray, b: np.ndarray | None = None) -> np.ndarray: ...
