"""Type stubs for ``hydrometlib.flux``.

Auto-generated from the module's signatures by ``make stubs``.
"""

from typing import overload

import numpy as np
import pandas as pd
import polars as pl

@overload
def latent_heat_flux(rn: pl.Expr, shf: pl.Expr, h: pl.Expr) -> pl.Expr: ...
@overload
def latent_heat_flux(rn: str, shf: str, h: str) -> pl.Expr: ...
@overload
def latent_heat_flux(rn: pl.Series, shf: pl.Series, h: pl.Series) -> pl.Series: ...
@overload
def latent_heat_flux(rn: pd.Series, shf: pd.Series, h: pd.Series) -> pd.Series: ...
@overload
def latent_heat_flux(rn: np.ndarray, shf: np.ndarray, h: np.ndarray) -> np.ndarray: ...
@overload
def evapotranspiration_from_latent_heat_flux(le: pl.Expr, ta: pl.Expr) -> pl.Expr: ...
@overload
def evapotranspiration_from_latent_heat_flux(le: str, ta: str) -> pl.Expr: ...
@overload
def evapotranspiration_from_latent_heat_flux(le: pl.Series, ta: pl.Series) -> pl.Series: ...
@overload
def evapotranspiration_from_latent_heat_flux(le: pd.Series, ta: pd.Series) -> pd.Series: ...
@overload
def evapotranspiration_from_latent_heat_flux(le: np.ndarray, ta: np.ndarray) -> np.ndarray: ...
