"""Type stubs for ``hydrometlib.meteorology``.

Auto-generated from the module's signatures by ``make stubs``.
"""

from typing import overload

import numpy as np
import pandas as pd
import polars as pl

@overload
def net_radiation(swin: pl.Expr, swout: pl.Expr, lwin: pl.Expr, lwout: pl.Expr) -> pl.Expr: ...
@overload
def net_radiation(swin: str, swout: str, lwin: str, lwout: str) -> pl.Expr: ...
@overload
def net_radiation(swin: pl.Series, swout: pl.Series, lwin: pl.Series, lwout: pl.Series) -> pl.Series: ...
@overload
def net_radiation(swin: pd.Series, swout: pd.Series, lwin: pd.Series, lwout: pd.Series) -> pd.Series: ...
@overload
def net_radiation(swin: np.ndarray, swout: np.ndarray, lwin: np.ndarray, lwout: np.ndarray) -> np.ndarray: ...
@overload
def mean_soil_heat_flux(g1: pl.Expr, g2: pl.Expr) -> pl.Expr: ...
@overload
def mean_soil_heat_flux(g1: str, g2: str) -> pl.Expr: ...
@overload
def mean_soil_heat_flux(g1: pl.Series, g2: pl.Series) -> pl.Series: ...
@overload
def mean_soil_heat_flux(g1: pd.Series, g2: pd.Series) -> pd.Series: ...
@overload
def mean_soil_heat_flux(g1: np.ndarray, g2: np.ndarray) -> np.ndarray: ...
@overload
def mean_sea_level_pressure(pa: pl.Expr, ta: pl.Expr, altitude: float) -> pl.Expr: ...
@overload
def mean_sea_level_pressure(pa: str, ta: str, altitude: float) -> pl.Expr: ...
@overload
def mean_sea_level_pressure(pa: pl.Series, ta: pl.Series, altitude: float) -> pl.Series: ...
@overload
def mean_sea_level_pressure(pa: pd.Series, ta: pd.Series, altitude: float) -> pd.Series: ...
@overload
def mean_sea_level_pressure(pa: np.ndarray, ta: np.ndarray, altitude: float) -> np.ndarray: ...
@overload
def absolute_humidity(ta: pl.Expr, rh: pl.Expr) -> pl.Expr: ...
@overload
def absolute_humidity(ta: str, rh: str) -> pl.Expr: ...
@overload
def absolute_humidity(ta: pl.Series, rh: pl.Series) -> pl.Series: ...
@overload
def absolute_humidity(ta: pd.Series, rh: pd.Series) -> pd.Series: ...
@overload
def absolute_humidity(ta: np.ndarray, rh: np.ndarray) -> np.ndarray: ...
@overload
def solar_zenith(time: pl.Expr, latitude: float) -> pl.Expr: ...
@overload
def solar_zenith(time: str, latitude: float) -> pl.Expr: ...
@overload
def solar_zenith(time: pl.Series, latitude: float) -> pl.Series: ...
@overload
def solar_zenith(time: pd.Series, latitude: float) -> pd.Series: ...
@overload
def solar_zenith(time: np.ndarray, latitude: float) -> np.ndarray: ...
@overload
def albedo(swin: pl.Expr, swout: pl.Expr, solar_zenith_angle: pl.Expr) -> pl.Expr: ...
@overload
def albedo(swin: str, swout: str, solar_zenith_angle: str) -> pl.Expr: ...
@overload
def albedo(swin: pl.Series, swout: pl.Series, solar_zenith_angle: pl.Series) -> pl.Series: ...
@overload
def albedo(swin: pd.Series, swout: pd.Series, solar_zenith_angle: pd.Series) -> pd.Series: ...
@overload
def albedo(swin: np.ndarray, swout: np.ndarray, solar_zenith_angle: np.ndarray) -> np.ndarray: ...
@overload
def is_snow_day(albedo_expr: pl.Expr, albedo_min_threshold: float, albedo_max_threshold: float) -> pl.Expr: ...
@overload
def is_snow_day(albedo_expr: str, albedo_min_threshold: float, albedo_max_threshold: float) -> pl.Expr: ...
@overload
def is_snow_day(albedo_expr: pl.Series, albedo_min_threshold: float, albedo_max_threshold: float) -> pl.Series: ...
@overload
def is_snow_day(albedo_expr: pd.Series, albedo_min_threshold: float, albedo_max_threshold: float) -> pd.Series: ...
@overload
def is_snow_day(albedo_expr: np.ndarray, albedo_min_threshold: float, albedo_max_threshold: float) -> np.ndarray: ...
